# https://toml.io/ja/v1.0.0
# 注：TOML は Python ではありませんので、ここでは Python の文法を使用しないでください。
# 例：TOML のブール値は小文字でなければならないです。

[module_coin]
# モジュールの設定項目です。ここに入力された値は、メッセージ内にプレーンテキストで表示されます。この部分には機密情報を入力しないでください。
coin_limit = 10000 # coin モジュールは、コイン投げの上限数。
coin_faceup_weight = 4997 # coin モジュールは、コインを投げたときの表の重さ。
coin_facedown_weight = 4997 # coin モジュールは、コインを投げたときの裏の重さ。
coin_stand_weight = 6 # coin モジュールは、コインを投げたときに立ち上がるの重さ。
