# https://toml.io/en/v1.0.0
# NOTE: TOML is not like Python. Do not use Python syntax here.
# EXAMPLE: Boolean values in TOML must be lowercase.

default_locale = "en_us" # Default session language environment.
config_version = 2 # Config version number, which will be automatically updated with the features and generally does not need to be modified.
