# https://toml.io/en/v1.0.0
# NOTE: TOML is not like Python. Do not use Python syntax here.
# EXAMPLE: Boolean values in TOML must be lowercase.

[module_weekly]
# The basic config section of the module. The value ​​filled in here can be displayed in the message. Please do not fill in sensitive information in this section.
ysarchives_user_agent = "" # User agent string used when requesting the YsArchives Biweekly RSS feed. Leave empty to avoid overriding the default.
