# https://toml.io/cn/v1.0.0
# 注意：TOML 不是 Python。请不要在此处使用 Python 语法。
# 例如：TOML 中的布尔值必须是小写。

[module_weekly]
# 模块的配置部分，此处填写的值可在消息中以明文形式展示。请不要在此部分填写敏感信息。
ysarchives_user_agent = "" # 请求有兽档案馆双周报 RSS 时使用的 User-Agent 字符串。留空则不覆盖默认值。
